import Head from "next/head";
import { useState } from "react";
import axios from "axios";

export default function Cadastrar() {
  const [data, setData] = useState({
    name: "",
    email: "",
  });

  const [message, setMessage] = useState("");

  const valueInput = (e) =>
    setData({ ...data, [e.target.name]: e.target.value });

  const addUser = async (e) => {
    e.preventDefault();
    //console.log("enviar para api");
    //console.log("Nome do usuario: " + data.name);
    //console.log("E-mail do usuario: " + data.email);

    const headers = {
      headers: {
        "Content-Type": "application/json",
      },
    };
    await axios
      .post("http://localhost:8080/users", data, headers)
      .then((response) => {
        setMessage(response.data.mensagem);

        setData({
          name: "",
          email: "",
        });
      })
      .catch((err) => {
        if (err.response) {
          setMessage(err.response.data.mensagem);
        } else {
          setMessage(
            "Erro: Tente novamente mais tarde ou entre em contato com administrador"
          );
        }
      });
  };

  return (
    <>
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={"/"}>
          <button type="button">Listar</button>
        </Link>

        <h2>Cadastrar Usuário</h2>

        {message ? <p>{message}</p> : ""}

        <form onSubmit={addUser}>
          <lable>Nome: </lable>
          <input
            type="text"
            name="name"
            placeholder="Digite o nome"
            onChange={valueInput}
            value={data.name}
          />
          <br />
          <br />
          <lable>E-mail: </lable>
          <input
            type="email"
            name="email"
            placeholder="Digite o Email"
            onChange={valueInput}
            value={data.email}
          />
          <br />
          <br />
          <button type="submit">Enviar</button> <br />
          <br />
        </form>
      </main>
    </>
  );
}
